spring:
  secret:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    auth:
      expiration:
        activation:
        refresh: 3
        recovery:
    defer-datasource-initialization: true
  mail:
    from:
    host:
    port:
    username:
    password:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
            scope:
              - https://www.googleapis.com/auth/classroom.coursework.me
              - https://www.googleapis.com/auth/classroom.announcements
              - https://www.googleapis.com/auth/classroom.coursework.students
              - https://www.googleapis.com/auth/classroom.profile.emails
              - https://www.googleapis.com/auth/classroom.rosters.readonly
              - https://www.googleapis.com/auth/classroom.courses.readonly
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname:  "org.jasypt.iv.NoIvGenerator"

default:
  initialize: false
  firstname:
  lastname:
  email:
  password:

server:
  error:
    include-stacktrace: never
  servlet:
    encoding:
      charset: UTF-8

token:
  time: 86400000
